const galleryItems = [
  {
    id: 1,
    title: "Dreamscape",
    description: "Fondo inspirado en la foto de Charles O'Rear, usada como fondo de Windows XP.",
    category: "naturaleza",
    year: "2004",
    image: "/windows.png",
    tags: ["Windows XP", "wallpaper", "naturaleza"],
  },
  {
    id: 2,
    title: "Frutiger Bubble",
    description: "Las esferas translúcidas con reflejos internos fueron el icono visual del Frutiger Aero.",
    category: "tech",
    year: "2006",
    image: "/frutiger-aero1.jpg",
    tags: ["cleancore", "3D", "tech"],
  },
  {
    id: 3,
    title: "Frutiger Aqua",
    description: "El agua limpia simbolizaba pureza tecnológica y un mundo sin contaminación.",
    category: "naturaleza",
    year: "2005",
    image: "/water.jpg",
    tags: ["agua", "pureza", "naturaleza"],
  },
  {
    id: 4,
    title: "Vista",
    description: "Ventanas con efecto de vidrio y gradientes suaves. El lenguaje visual de Windows Vista.",
    category: "tech",
    year: "2007",
    image: "/vista.jpg",
    tags: ["Windows Vista", "Aero Glass", "Era"],
  },
  {
    id: 5,
    title: "Cyber",
    description: "Una epoca Cyber donde se romantizaba la idea de una vida junto a los robots",
    category: "tech",
    year: "2003",
    image: "/cyber.jpg",
    tags: ["cyber", "tecno", "futurista"],
  },
  {
    id: 6,
    title: "Metro",
    description: "Uno de los estilos mas destacados del Frutiger aero por sus caracteristicos colores y detalles urban",
    category: "fashion",
    year: "2007",
    image: "/metro.jpg",
    tags: ["urban", "tecno", "futurista"],
  },
  {
    id: 7,
    title: "Dorfic",
    description: "Ilusiones naranjas que prometian un futuro brillante, simbolo del optimismo",
    category: "fashion",
    year: "2008",
    image: "/dorfic.jpg",
    tags: ["color", "vision", "futurista"],
  },
  {
    id: 8,
    title: "Technozen",
    description: "Lo que antes era un estilo de vida, tambien a ser un estilo de musica, que imita la musica electronica y home de los 2000",
    category: "musica y arte",
    year: "2009",
    image: "/tech.jpg",
    tags: ["home", "tecno", "musica"],
  },
  {
    id: 9,
    title: "DarkAero",
    description: "Una romantizacion distintiva del Frutiger Aero que se caracteriza por tonos oscuros, brillantes y llamativos",
    category: "tech",
    year: "2007",
    image: "/dark.jpg",
    tags: ["negro", "glass", "futurista"],
  },
];

export default galleryItems;